import PDFDocument from "pdfkit";
import { APP_NAME } from "@/lib/brand";

export type TodayReportPdfInput = {
  date: string;
  total: number;
  completed: number;
  inProgress: number;
  pending: number;
  overdue: number;
  progress: number;
  completedTitles: string[];
  remainingTitles: string[];
  generatedBy?: string;
};

export async function buildTodayReportPdf(input: TodayReportPdfInput): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(16).fillColor("#0f172a").text(APP_NAME, { align: "left" });
    doc.moveDown(0.3);
    doc.fontSize(11).fillColor("#64748b").text(`Today report · ${input.date}`);
    if (input.generatedBy) {
      doc.fontSize(9).text(`Generated by ${input.generatedBy}`);
    }
    doc.moveDown(1);

    doc.fontSize(12).fillColor("#0f172a").text("Overview");
    doc.moveDown(0.4);
    doc.fontSize(10).fillColor("#334155");
    doc.text(
      `Total ${input.total}  ·  Done ${input.completed}  ·  Active ${input.inProgress}  ·  Pending ${input.pending}  ·  Overdue ${input.overdue}`,
    );
    doc.text(`Progress ${input.progress}%`);
    doc.moveDown(1);

    doc.fontSize(12).fillColor("#0f172a").text("Completed");
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor("#334155");
    if (input.completedTitles.length === 0) {
      doc.text("- none");
    } else {
      for (const title of input.completedTitles) {
        doc.text(`- ${title}`);
      }
    }
    doc.moveDown(1);

    doc.fontSize(12).fillColor("#0f172a").text("Remaining");
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor("#334155");
    if (input.remainingTitles.length === 0) {
      doc.text("- none");
    } else {
      for (const title of input.remainingTitles) {
        doc.text(`- ${title}`);
      }
    }

    doc.end();
  });
}
